books = [
    {
        "id": 2,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2019-05-03",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2015-08-20",
        "page_count": 792,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Addison-Wesley",
        "published_date": "2019-11-27",
        "page_count": 480,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 6,
        "title": "The Pragmatic Programmer",
        "author": "David Thomas",
        "publisher": "Addison-Wesley",
        "published_date": "2019-10-30",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Design Patterns",
        "author": "Gang of Four",
        "publisher": "Addison-Wesley",
        "published_date": "1994-10-31",
        "page_count": 395,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Think Python",
        "author": "Allen B Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
]
